### PR TITLE
Refactor serialization to remove the need for direct access by provid…

### PR DESCRIPTION
**Pull request by aweisberg**
…ing a ByteBuffer that points to the off heap memory. Keep direct access for get to allow the caller to lazily deref and deserialize

### CODE REVIEW

**Comment by snazy** [comment]
patch generally LGTM

* ohc-jmh module doesn't compile. Can you add ``java.nio.ByteBuffer`` to the imports in ``org.caffinitas.ohc.jmh.Utils``?
* You can also remove the throws clause on the ``CacheSerializer`` methods and remove all ``catch (IOException)`` - makes the code even better. IOException is no longer necessary since we're no longer dealing with streams.

Waiting on Benedict's feedback. When he's fine with the patch, I can quickly do a release containing this PR.

**Comment by aweisberg** [comment]
Removing IOException pushes the complexity into the key/value serializers which are in many cases going to call things that do throw IOException. I would like to leave it.

Working on the array changes now.

**Comment by aweisberg** [comment]
Updated to fix the array issue

**Comment by snazy** [comment]
Right - it moves some handling to the serializers. But that ``IOException`` is always caught by ``OHCacheImpl`` and immediately rethrown (wrapped in a ``RuntimeException`` or ``IOError``). I mean - if serializers use something that throws ``IOException``, it's up to them to handle that. OHC cannot handle that. The change is a breaking change anyway - so I'd really like to see that ``throws IOException`` go away.

**Comment by aweisberg** [comment]
OK, removed the IOException

**Comment by snazy** [comment]
thanks :)

**Comment by snazy** [comment]
Thanks for the PR! It makes OHC code much nicer and improves access to cached data.

Merged in 3c1ea00e69d14ec64a8887b33f16219bac33c6c5

**Pull request closed without merging**
